#!/usr/bin/env python3
"""
Generate master KB_INDEX.md cross-referencing all knowledge assets.
"""
import json
from pathlib import Path
from datetime import datetime

KNOWLEDGE = Path(__file__).parent.parent / 'knowledge'
OUTPUT = KNOWLEDGE / 'KB_INDEX.md'

def count_files(dir_path, extensions=('.json', '.md')):
    """Count files with given extensions in directory."""
    if not dir_path.exists():
        return 0, []
    files = []
    for ext in extensions:
        files.extend(dir_path.glob(f'*{ext}'))
    # Remove duplicates (same basename .json/.md)
    basenames = {f.stem for f in files}
    return len(basenames), sorted(basenames)

def main():
    sections = []
    
    # Tables
    tables_dir = KNOWLEDGE / 'tables'
    tables_count, tables_files = count_files(tables_dir, ('.json',))
    sections.append(('Tables', tables_count, tables_files))
    
    # Forms
    forms_dir = KNOWLEDGE / 'forms'
    forms_count, forms_files = count_files(forms_dir, ('.json', '.md'))
    sections.append(('Forms', forms_count, forms_files))
    
    # Menus
    menus_dir = KNOWLEDGE / 'menus'
    menus_count, menus_files = count_files(menus_dir, ('.md',))
    sections.append(('Menus', menus_count, menus_files))
    
    # Libs (Object Libraries)
    libs_dir = KNOWLEDGE / 'libs'
    libs_count, libs_files = count_files(libs_dir, ('.json', '.md'))
    sections.append(('Libraries', libs_count, libs_files))
    
    # Reports
    reports_dir = KNOWLEDGE / 'reports'
    reports_count, reports_files = count_files(reports_dir, ('.json', '.md'))
    sections.append(('Reports', reports_count, reports_files))
    
    # Procedures (PL/SQL packages)
    procedures_dir = KNOWLEDGE / 'procedures'
    procedures_count, procedures_files = count_files(procedures_dir, ('.json', '.md'))
    sections.append(('Procedures', procedures_count, procedures_files))
    
    # SQL scripts
    sql_dir = KNOWLEDGE / 'sql'
    sql_count, sql_files = count_files(sql_dir, ('.sql',))
    sections.append(('SQL Scripts', sql_count, sql_files))
    
    # Generate markdown
    lines = []
    lines.append("# ERP Brain Knowledge Base Index")
    lines.append("")
    lines.append(f"*Generated: {datetime.utcnow().isoformat()}Z*")
    lines.append("")
    
    total_items = sum(count for _, count, _ in sections)
    lines.append(f"**Total knowledge assets:** {total_items}")
    lines.append("")
    
    for name, count, files in sections:
        lines.append(f"## {name} ({count})")
        if count == 0:
            lines.append("*(none)*")
        else:
            for f in files[:50]:  # limit to 50 per section
                lines.append(f"- `{f}`")
            if len(files) > 50:
                lines.append(f"- ... and {len(files) - 50} more")
        lines.append("")
    
    lines.append("---")
    lines.append("This index is auto-generated by `scripts/generate_kb_index.py`.")
    
    OUTPUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f"Generated {OUTPUT} with {total_items} total assets")
    
    # Also update PROJECT_MANIFEST.md
    manifest_path = Path(__file__).parent.parent / 'docs' / 'PROJECT_MANIFEST.md'
    if manifest_path.exists():
        content = manifest_path.read_text(encoding='utf-8')
        # Update status line
        if '**Status:**' in content:
            lines_manifest = content.splitlines()
            for i, line in enumerate(lines_manifest):
                if line.startswith('**Status:**'):
                    lines_manifest[i] = '**Status:** Complete'
                    break
            # Update "What's Live" section
            # Simple approach: replace entire section
            # We'll just append a note for now
            lines_manifest.append('')
            lines_manifest.append('### Knowledge Base Live')
            lines_manifest.append(f'- Tables: {tables_count} tables')
            lines_manifest.append(f'- Forms: {forms_count} forms')
            lines_manifest.append(f'- Menus: {menus_count} menus')
            lines_manifest.append(f'- Libraries: {libs_count} object libraries')
            lines_manifest.append(f'- Reports: {reports_count} reports')
            lines_manifest.append(f'- Procedures: {procedures_count} PL/SQL packages')
            lines_manifest.append(f'- SQL Scripts: {sql_count} scripts')
            lines_manifest.append(f'- Total: {total_items} assets')
            lines_manifest.append(f'- Index: [KB_INDEX.md](../knowledge/KB_INDEX.md)')
            manifest_path.write_text('\n'.join(lines_manifest), encoding='utf-8')
            print(f"Updated {manifest_path}")

if __name__ == '__main__':
    main()